
<div class="block block-customer-login">
  
    <div class="block-title">
       <h2><?php echo __('Add Details'); ?></h2>
    </div>
    <div class="block-content" aria-labelledby="block-heading">
    <form class="form"
              action=""
              method="post"
              id="edit-form"
              data-mage-init='{"validation":{}}'>
              <fieldset class="fieldset" data-hasrequired="<?php  echo __('* Required Fields') ?>">
                <div class="field title required">
                <label class="label" for="title"><span><?php  echo __('Title') ?></span>
                </label>
                <div class="control">
                        <input name="data[title]" id="title" type="text" class="input-text" title="<?php  echo __('Title') ?>" data-validate="{required:true}" />
               </div>
               </div>
               <div class="field email required">
               <label class="label" for="Email"><span><?php echo __('Email')?></span></label>
               <div class="control">
                         <input name="data[email]" id="email" type="email" class="input-text" title="<?php echo __('Email')?>" data-validate="{required:true}"/>
               </div>
               </div>
               <div class="field status required">
               <label class="label" for="status"><span><?php echo __('Status')?></span></label>
               <div class="control">
                    <select name="data[IsActive]" id="IsActive" class="input-text" title="<?php echo __('status')?>">
                    <option value="1">Enable</option>
                    <option value="2">Disable</option>
                    </select>
               </div>
               </div>
               <div class="actions-toolbar">
                    <div class="primary"><input type="submit" class="action login primary" name="data[submit]" id="send2" value="<?php  echo __('Save') ?>" /></div>
                    <div class="secondary"><a class="action remind" href="<?php echo $block->getListUrl(); ?>"><span><?php  echo __('Go back to list') ?></span></a></div>
                </div>
                </fieldset>
                </form>

        </div>
</div> 
