<?php  
$arr=$block->getTestModel()->getData();
?>

<div class="table-wrapper orders-history">
<form class="form"
      method="post"
      action="<?php echo $block->getAddUrl()?>">
<table class="data table table-order-items history" id="my-orders-table">
    <thead>
       <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col title"><?php  echo __('Title') ?></th>
            <th scope="col" class="col email"><?php  echo __('Email') ?></th>
            <th scope="col" class="col create_time"><?php echo __('create_time') ?></th>
            <th scope="col" class="col update_time"><?php echo __('update_time') ?></th>
            <th scope="col" class="col status"><?php  echo __('Status') ?></th>
            <th scope="col" class="col actions"><?php  echo __('Action') ?></th>
        </tr>
    </thead>
    <tbody>
<?php
foreach($arr as $data)
{
     print_r("<tr><td>".$data['excellence_table_test_id']."</td>");
     print_r("<td>".$data['title']."</td>");
     print_r("<td>".$data['email']."</td>");
     print_r("<td>".$data['creation_time']."</td>");
     print_r("<td>".$data['update_time']."</td>");
     if($data['is_active']==1){
        $option="Enabled";
     }
     else{
        $option="Disabled";
     }
     print_r("<td>".$option."</td>");
     print_r("<td>")?><a href="<?php echo $block->getEditUrl($data['excellence_table_test_id']);?>"><?php echo __('Edit');?></a>
     <?php
     print_r("</td>");
     ?>
     <?php
     print_r("<td>")?><a href="<?php echo $block->getDeleteUrl($data['excellence_table_test_id']); ?>"><?php echo __('Delete');?></a>
     <?php
     print_r("</tr>");

}
?>
</tbody>
</table>
<div class="actions-toolbar">
    <div class="primary"><button type="submit" class="action submit primary" name="add" id="add"><span><?php echo __('Add New')?></span></button></div>
</div>

</form>

</div>
















