<?php  
$arr=$block->getTestModel()->getData();
// print_r($arr);

?>
<form class="form>"
      method="post"
      action="<?php echo $block->getAddUrl()?>">
<table><th>Id</th><th>Title</th><th>Email</th><th>Create_Time</th><th>Update_time</th><th>is_Active</th>
<?php
foreach($arr as $data)
{
     print_r("<tr><td>".$data['excellence_table_test_id']."</td>");
     print_r("<td>".$data['title']."</td>");
     print_r("<td>".$data['email']."</td>");
     print_r("<td>".$data['creation_time']."</td>");
     print_r("<td>".$data['update_time']."</td>");
     print_r("<td>".$data['is_active']."</td>");
     print_r("<td>")?><a href="<?php echo $block->getEditUrl($data['excellence_table_test_id']);?>"><?php echo __('Edit');?></a>
     <?php
     print_r("</td>");
     ?>
     <?php
     print_r("<td>")?><a href="<?php echo $block->getDeleteUrl($data['excellence_table_test_id']); ?>"><?php echo __('Delete');?></a>
     <?php
     print_r("</tr>");

}
?>
</table>
<div class="actions-toolbar" align="center">
    <div class="primary"><button type="submit" class="action submit primary" name="add" id="add" onc><span><?php /* @escapeNotVerified */ echo __('Add New')?></span></button>
    </div>
</div>
</form>
<!--<div class="actions-toolbar">
    <div class="primary"><button type="submit" class="action submit primary" name="add" id="add" onc><span><?php /* @escapeNotVerified */ 
    //echo __('Add New')?></span></button>
    </div>
</div>-->















